name: Test Build

on:
  workflow_call:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup | Force release branch to be at workflow sha
        run: |
          git reset --hard ${{ github.sha }}

      - name: Setup
        run: |
          echo "[tool.semantic_release.branches.test]" >> pyproject.toml
          echo "match = '$GITHUB_REF_NAME'" >> pyproject.toml

      - name: Python Semantic Release Noop Check
        uses: python-semantic-release/python-semantic-release@v10.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          no_operation_mode: true
