name: Test Pipeline

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  black:
    uses: ./.github/workflows/black.yml

  isort:
    uses: ./.github/workflows/isort.yml

  unit_tests:
    uses: ./.github/workflows/unit-tests.yml

  test_build:
    uses: ./.github/workflows/test-build.yml
